<?php
    $configName = array();

    $configName["clarin.at:icltt:ddc:traum_deu"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:traum_deu", "displayText" => "Freud: Die Traumdeutung, German", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "traum_deu");
    $configName["clarin.at:icltt:ddc:traum_russ"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:traum_russ", "displayText" => "Freud: Die Traumdeutung, Russian", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "traum_russ");
    $configName["clarin.at:icltt:ddc:idiot"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:idiot", "displayText" => "Dostojewski: Idiot, Russian", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "idiot");
    $configName["clarin.at:icltt:ddc:geier"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:geier", "displayText" => "Dostojewski: Idiot, Geier", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "geier");
    $configName["clarin.at:icltt:ddc:herboth"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:herboth", "displayText" => "Dostojewski: Idiot, Herboth", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "herboth");
    $configName["clarin.at:icltt:ddc:rahsin"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:rahsin", "displayText" => "Dostojewski: Idiot, Rahsin", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "rahsin");
    $configName["clarin.at:icltt:ddc:barock"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:barock", "displayText" => "Barocktexte", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "barock");
    $configName["clarin.at:icltt:ddc:c4"] = array("endPoint" => "http://corpus3.aac.ac.at/ddconsru", "name" => "clarin.at:icltt:ddc:c4", "displayText" => "C4 Vienna", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "c4");
    $configName["clarin.at:icltt:cr:stb"] = array("endPoint" => "http://clarin.aac.ac.at/exist8/rest/db/cr/cr.xql", "name" => "clarin.at:icltt:cr:stb", "displayText" => "Schnitzler Tagebuch", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "stb");
    $configName["clarin.at:icltt:cr:barock"] = array("endPoint" => "http://clarin.aac.ac.at/exist8/rest/db/cr/cr.xql", "name" => "clarin.at:icltt:cr:barock", "displayText" => "Barock Texte", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "barock");
    $configName["clarin.at:icltt:cr:aac-names"] = array("endPoint" => "http://clarin.aac.ac.at/exist8/rest/db/cr/cr.xql", "name" => "clarin.at:icltt:cr:aac-names", "displayText" => "Namensdatenbank", "type" => "fcs.resource", "style" => "http://corpus3.aac.ac.at/cs2/corpus_shell/xsl/result2view_v1.xsl", "context" => "aac-names");
    
?>