<?php

namespace ACDH\FCSSRU;

require_once __DIR__ .  '/../../../modules/utils-php/IndentDomDocument.php';

use ACDH\FCSSRU\IndentDomDocument;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-23 at 16:05:44.
 */
class IndentDomDocumentTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IndentDomDocument
     */
    protected $object;
    protected $xmlExample1 = "<?xml version='1.0'?>\n<this attr='that'><foo>lkjalksjdlakjdlkasd</foo><foo>lkjlkasjlkajklajslk</foo></this>";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IndentDomDocument;
        $this->object->loadXML($this->xmlExample1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IndentDomDocument::xmlIndent
     * @todo   Implement testXmlIndent().
     */
    public function testXmlIndent() {
        $this->object->xmlIndent();
        $this->assertEquals("<?xml version=\"1.0\"?>\n".
"<this attr=\"that\">\n".
"\t<foo>lkjalksjdlakjdlkasd</foo>\n".
"\t<foo>lkjlkasjlkajklajslk</foo>\n".
"</this>\n", $this->object->saveXML());
        $this->object->setWhiteSpaceForIndentation("    ")->xmlIndent();
        $this->assertEquals("<?xml version=\"1.0\"?>\n".
"<this attr=\"that\">\n".
"    <foo>lkjalksjdlakjdlkasd</foo>\n".
"    <foo>lkjlkasjlkajklajslk</foo>\n".
"</this>\n", $this->object->saveXML());        
    }

}
