<?php
    /**
	 * This file contains an array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * This file is generated by initconfigcache.php. Load initconfigcache.php at least once from your web server with your browser. 
	 * @package fcs-aggregator
	 */
	 
	/**
	 * An array of arrays (a map of maps) for finding endpoints by their identifier
	 * 
	 * Using the identifier for a resource the endPoint, name (back reference, the identifier),
	 * displayText (human intelligable name),
	 * type ("fcs.resource"), style (the stylesheet associated with the resource) and context 
	 * (for the x-context parameter can be determined). 
	 * @global array $configName
	 */
    $configName = array();

	die("The file fcs.resource.config.php needs to be generated once! <br/> Either click <a href='initconfigcache.php'>here </a> or alternatively you can just remove it.");
    
?>